version: '3'
services:
    pia:
        image: qmcgaw/private-internet-access
        container_name: pia
        cap_add:
            - NET_ADMIN
        networks:
            - pianet
        volumes:
            - ./auth.conf:/auth.conf:ro
        environment:
            - PROTOCOL=tcp
            - ENCRYPTION=strong
            - REGION=London
        restart: always
    deluge:
        image: linuxserver/deluge
        restart: always
        networks:
            - pianet
        volumes:
            - ./downloads:/downloads 
            - ./config:/config 
        environment:
            - TZ=London/Europe
    nginx:
        image: nginx:alpine
        restart: always
        networks:
            - pianet
        ports:
           - 8112:80
        links:
            - pia:deluge
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

networks:
    pianet:
        external: true