version: '3'
services:
    pia:
        image: qmcgaw/private-internet-access
        container_name: pia
        cap_add:
            - NET_ADMIN
        networks:
            - pianet
        volumes:
            - ./auth.conf:/auth.conf
        environment:
            - PROTOCOL=tcp
            - ENCRYPTION=strong
            - REGION=Switzerland
        restart: always
    deluge:
        image: linuxserver/deluge
        restart: always
        network_mode: "service:pia"
        volumes:
            - /data/Everything Else/Torrents/Downloads:/downloads
            - ./config:/config 
        environment:
            - TZ=London/Europe
    jackett:
        image: linuxserver/jackett
        restart: always
        network_mode: "service:pia"
        volumes: 
           - ./config-jackett:/config
           - /data/Everything Else/Torrents/Downloads:/downloads
        environment:
           - TZ=London/Europe
    nginx:
        image: nginx:alpine
        restart: always
        networks:
            - pianet
        ports:
           - 8112:80
        links:
            - pia:deluge
            - pia:jackett
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

networks:
    pianet:
        external: true
